task:
  name: "Generate AOSP to main branch"
  timeout_in: 120m
  container:
    image: openjdk:24-slim
    privileged: true
    cpu: 4
    memory: 16G
  script: |
    git clone https://github.com/aldrin1127/gamestar.git
    cd gamestar
    ./cirrus-ci.sh
